import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 15, paddingVertical: 10, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  backButton: { fontSize: 24, color: '#333' },
  headerTitle: { alignItems: 'center' },
  regionText: { fontSize: 18, fontWeight: 'bold', color: '#1F2937' },
  dateRangeText: { fontSize: 14, color: '#6B7280', marginTop: 4 },
  headerActions: { flexDirection: 'row', gap: 15 },
  actionButton: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center' },
  actionButtonText: { fontSize: 18 },
  tabContainer: { flexDirection: 'row', backgroundColor: '#FFFFFF' },
  tab: { flex: 1, paddingVertical: 15, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  activeTab: { borderBottomColor: '#3B82F6' },
  tabText: { fontSize: 16, color: '#6B7280' },
  activeTabText: { color: '#3B82F6', fontWeight: '600' },
  scheduleContent: { flex: 1 },
  mapContainer: { height: 200, margin: 15, borderRadius: 10, overflow: 'hidden', borderWidth: 1, borderColor: '#E5E7EB' },
  dateSection: { paddingVertical: 10, paddingHorizontal: 15, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  dayButton: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 20, backgroundColor: '#E5E7EB', marginRight: 10 },
  activeDayButton: { backgroundColor: '#3B82F6' },
  dayButtonText: { color: '#374151', fontWeight: '500' },
  activeDayButtonText: { color: '#FFFFFF' },
  scheduleItem: { backgroundColor: '#FFFFFF', padding: 20, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  scheduleInfo: { flex: 1 },
  locationText: { fontSize: 16, fontWeight: '600', color: '#1F2937', marginBottom: 4 },
  timeText: { fontSize: 14, color: '#6B7280', marginBottom: 6 },
  descriptionText: { fontSize: 14, color: '#4B5563' },
  rowBack: { alignItems: 'center', backgroundColor: '#EF4444', flex: 1, flexDirection: 'row', justifyContent: 'flex-end' },
  backRightBtn: { alignItems: 'center', bottom: 0, justifyContent: 'center', position: 'absolute', top: 0, width: 75 },
  backRightBtnRight: { backgroundColor: '#EF4444', right: 0 },
  backTextWhite: { color: '#FFF', fontWeight: '600' },
  chatMessages: { flex: 1, padding: 10 },
  myMessageContainer: { alignSelf: 'flex-end', marginBottom: 10, alignItems: 'flex-end' },
  otherMessageContainer: { alignSelf: 'flex-start', marginBottom: 10, alignItems: 'flex-start' },
  myMessageBubble: { backgroundColor: '#007AFF', borderRadius: 15, paddingVertical: 10, paddingHorizontal: 15, maxWidth: '80%' },
  otherMessageBubble: { backgroundColor: '#f0f0f0', borderRadius: 15, paddingVertical: 10, paddingHorizontal: 15, maxWidth: '80%' },
  myMessageText: { color: '#fff', fontSize: 14 },
  sentToGptText: {
    fontSize: 12,
    color: '#999',
    marginBottom: 4,
  },
  otherMessageText: { fontSize: 14, color: '#333' },
  gptMessageContainer: {
    alignItems: 'center',
    marginBottom: 10,
  },
  gptMessageBubble: { 
    backgroundColor: '#1ABC9C', 
    borderRadius: 15, 
    paddingVertical: 10, 
    paddingHorizontal: 15, 
    maxWidth: '80%' 
  },
  gptMessageText: {
    color: '#fff',
    fontSize: 14,
  },
  inputContainer: { flexDirection: 'row', alignItems: 'flex-end', padding: 15, borderTopWidth: 1, borderTopColor: '#f0f0f0' },
  gptButton: { backgroundColor: '#f0f0f0', borderWidth: 1, borderColor: '#ccc', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 20, marginRight: 10, height: 40, justifyContent: 'center' },
  gptButtonActive: { backgroundColor: '#007AFF', borderColor: '#007AFF' },
  gptButtonText: { color: '#666', fontSize: 14, fontWeight: '500' },
  gptButtonTextActive: { color: '#fff' },
  messageInputContainer: { flex: 1, backgroundColor: '#f0f0f0', borderRadius: 20, paddingHorizontal: 15, paddingVertical: 10, marginRight: 10, minHeight: 40, justifyContent: 'center' },
  messageInputContainerActive: { backgroundColor: '#e0f7fa', borderWidth: 1, borderColor: '#007AFF' },
  messageInput: { fontSize: 14, color: '#333', padding: 0 },
  sendButton: { backgroundColor: '#007AFF', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 20, height: 40, justifyContent: 'center' },
  sendButtonText: { fontSize: 18, color: '#fff' },
  profileSection: { flexDirection: 'row', alignItems: 'center', marginBottom: 5 },
  profileImage: { width: 25, height: 25, borderRadius: 12.5, backgroundColor: '#e0e0e0', justifyContent: 'center', alignItems: 'center', marginRight: 8 },
  profileText: { fontSize: 14, color: '#333' },
  nicknameText: { fontSize: 14, color: '#666' },
  overlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.5)', zIndex: 1000 },
  slideMenu: { position: 'absolute', top: 0, bottom: 0, right: 0, width: 300, backgroundColor: '#ffffff', zIndex: 1001, shadowColor: '#000', shadowOffset: { width: -2, height: 0 }, shadowOpacity: 0.25, shadowRadius: 3.84, elevation: 5 },
  menuHeader: { flexDirection: 'row', justifyContent: 'flex-end', paddingHorizontal: 20, paddingTop: 60, paddingBottom: 20, borderBottomWidth: 1, borderBottomColor: '#e2e8f0' },
  closeButton: { fontSize: 24, color: '#666' },
  menuContent: { paddingTop: 20 },
  menuItem: { paddingVertical: 18, paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  menuText: { fontSize: 16, color: '#1a202c' },
  leaveTripContainer: { position: 'absolute', bottom: 50, left: 20, right: 20 },
  leaveTripButton: { paddingVertical: 15, paddingHorizontal: 20, borderTopWidth: 1, borderTopColor: '#e2e8f0' },
  leaveTripText: { fontSize: 16, color: '#e53e3e', textAlign: 'center' },
  emptyMessageContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  markerContainer: {
    backgroundColor: '#3B82F6',
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  markerText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  markerPin: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderBottomWidth: 15,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#3B82F6',
    transform: [{ rotate: '180deg' }],
    position: 'absolute',
    bottom: -5, // Adjust to position the triangle correctly
  },
});
