import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 20, paddingBottom: 15, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  backButton: { fontSize: 24, color: '#4a5568' },
  headerTitle: { alignItems: 'flex-start', flex: 1, marginLeft: 10 },
  regionText: { fontSize: 18, fontWeight: 'bold', color: '#1F2937' },
  dateRangeText: { fontSize: 14, color: '#6B7280', marginTop: 4 },
  headerActions: { flexDirection: 'row', gap: 15 },
  actionButton: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center' },
  actionButtonText: { fontSize: 18 },
  tabContainer: { flexDirection: 'row', backgroundColor: '#FFFFFF', paddingHorizontal: 10, paddingTop: 8, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: '#E5E7EB' },
  tabHalf: { flex: 1, alignItems: 'center' },
  tab: { paddingVertical: 10, paddingHorizontal: 72, borderRadius: 22, backgroundColor: 'transparent' },
  activeTab: { backgroundColor: '#DBEAFE' },
  tabText: { fontSize: 14, color: '#6B7280', fontWeight: '500' },
  activeTabText: { color: '#3B82F6', fontWeight: '700' },
  scheduleContent: { flex: 1 },
  mapContainer: { height: 200, marginHorizontal: 15, marginTop: 12, marginBottom: 12, borderRadius: 10, overflow: 'hidden', borderWidth: 1, borderColor: '#E5E7EB' },
  controlBar: { paddingVertical: 10, paddingHorizontal: 10, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#E5E7EB', flexDirection: 'row', alignItems: 'center' },
  dropdown: { borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 8, paddingVertical: 10, paddingHorizontal: 12, backgroundColor: '#ffffff', flexDirection: 'row', alignItems: 'center', marginRight: 10 },
  dropdownText: { fontSize: 14, color: '#1f2937' },
  dropdownArrow: { fontSize: 12, color: '#6b7280', marginLeft: 6 },
  editPlanLink: { marginLeft: 'auto' },
  editPlanLinkText: { color: '#3B82F6', fontSize: 14 },
  dayBadge: { marginLeft: 10, fontSize: 14, color: '#6B7280' },
  scheduleItem: { backgroundColor: '#FFFFFF', padding: 20, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  scheduleInfo: { flex: 1 },
  itemHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  navButton: { borderWidth: 1, borderColor: '#3B82F6', paddingVertical: 6, paddingHorizontal: 10, borderRadius: 8, backgroundColor: '#ffffff' },
  navButtonText: { color: '#3B82F6', fontSize: 13, fontWeight: '600' },
  locationText: { fontSize: 16, fontWeight: '600', color: '#1F2937', marginBottom: 4 },
  timeText: { fontSize: 14, color: '#6B7280', marginBottom: 6 },
  descriptionText: { fontSize: 14, color: '#4B5563' },
  rowBack: { alignItems: 'center', backgroundColor: '#EF4444', flex: 1, flexDirection: 'row', justifyContent: 'flex-end' },
  backRightBtn: { alignItems: 'center', bottom: 0, justifyContent: 'center', position: 'absolute', top: 0, width: 75 },
  backRightBtnRight: { backgroundColor: '#EF4444', right: 0 },
  backTextWhite: { color: '#FFF', fontWeight: '600' },
  chatMessages: { flex: 1, padding: 10, backgroundColor: '#F2F3F5' },
  myMessageContainer: { alignSelf: 'flex-end', marginBottom: 10, alignItems: 'flex-end' },
  otherMessageContainer: { alignSelf: 'flex-start', marginBottom: 10, alignItems: 'flex-start' },
  myMessageBubble: { backgroundColor: '#3A3A3C', borderRadius: 15, paddingVertical: 10, paddingHorizontal: 15, maxWidth: '80%' },
  otherMessageBubble: { backgroundColor: '#FFFFFF', borderRadius: 15, paddingVertical: 10, paddingHorizontal: 15, maxWidth: '80%' },
  myMessageText: { color: '#FFFFFF', fontSize: 14 },
  sentToGptText: {
    fontSize: 12,
    color: '#999',
    marginBottom: 4,
  },
  otherMessageText: { fontSize: 14, color: '#000000' },
  gptMessageBubble: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 15,
    maxWidth: '80%',
    borderWidth: 1,
    borderColor: '#000000',
  },
  gptMessageText: {
    color: '#000000',
    fontSize: 14,
  },
  gptProfileImage: {
    width: 25,
    height: 25,
    borderRadius: 12.5,
    marginRight: 8,
  },
  inputContainer: { flexDirection: 'row', alignItems: 'flex-end', padding: 15, borderTopWidth: 1, borderTopColor: '#f0f0f0' },
  gptButton: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#000000', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 20, marginRight: 10, height: 40, justifyContent: 'center' },
  gptButtonActive: { backgroundColor: '#007AFF', borderColor: '#007AFF' },
  gptButtonText: { color: '#666', fontSize: 14, fontWeight: '500' },
  gptButtonTextActive: { color: '#fff' },
  messageInputContainer: { flex: 1, backgroundColor: '#FFFFFF', borderRadius: 20, paddingHorizontal: 15, paddingVertical: 10, marginRight: 10, minHeight: 40, justifyContent: 'center', borderWidth: 1, borderColor: '#000000' },
  messageInputContainerActive: { backgroundColor: '#e0f7fa', borderWidth: 1, borderColor: '#007AFF' },
  messageInput: { fontSize: 14, color: '#333', padding: 0 },
  sendButton: { backgroundColor: '#FFFFFF', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 20, height: 40, justifyContent: 'center' },
  sendButtonText: { fontSize: 18, color: '#fff' },
  profileSection: { flexDirection: 'row', alignItems: 'center', marginBottom: 5 },
  profileImage: { width: 25, height: 25, borderRadius: 12.5, backgroundColor: '#e0e0e0', justifyContent: 'center', alignItems: 'center', marginRight: 8 },
  profileText: { fontSize: 14, color: '#333' },
  nicknameText: { fontSize: 14, color: '#666' },
  overlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.5)', zIndex: 1000 },
  slideMenu: { position: 'absolute', top: 0, bottom: 0, right: 0, width: 300, backgroundColor: '#ffffff', zIndex: 1001, shadowColor: '#000', shadowOffset: { width: -2, height: 0 }, shadowOpacity: 0.25, shadowRadius: 3.84, elevation: 5 },
  menuHeader: { flexDirection: 'row', justifyContent: 'flex-end', paddingHorizontal: 20, paddingTop: 60, paddingBottom: 20, borderBottomWidth: 1, borderBottomColor: '#e2e8f0' },
  closeButton: { fontSize: 24, color: '#666' },
  menuContent: { paddingTop: 20 },
  menuItem: { paddingVertical: 18, paddingHorizontal: 20, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  menuText: { fontSize: 16, color: '#1a202c' },
  leaveTripContainer: { position: 'absolute', bottom: 50, left: 20, right: 20 },
  leaveTripButton: { paddingVertical: 15, paddingHorizontal: 20, borderTopWidth: 1, borderTopColor: '#e2e8f0' },
  leaveTripText: { fontSize: 16, color: '#e53e3e', textAlign: 'center' },
  emptyMessageContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  markerContainer: {
    backgroundColor: '#3B82F6',
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  markerText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  markerPin: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderBottomWidth: 15,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#3B82F6',
    transform: [{ rotate: '180deg' }],
    position: 'absolute',
    bottom: -5, // Adjust to position the triangle correctly
  },
  // --- Detail Modal Styles ---
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  modalCloseButton: {
    padding: 5,
  },
  modalCloseButtonText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  modalImage: {
    width: '95%',
    height: 250,
    resizeMode: 'cover',
    borderRadius: 12,
    alignSelf: 'center',
  },
  modalImagePlaceholder: {
    width: '95%',
    height: 250,
    backgroundColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    alignSelf: 'center',
  },
  modalContent: {
    padding: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#1F2937',
  },
  modalSection: {
    marginBottom: 15,
  },
  modalSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  modalSectionText: {
    fontSize: 16,
    color: '#4B5563',
    lineHeight: 24,
  },
  generateButton: {
    backgroundColor: '#3B82F6',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  generateButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  // --- Modal Footer Buttons ---
  modalFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    flexDirection: 'row',
  },
  outlineButton: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: '#111827',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 10,
  },
  outlineButtonText: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '600',
  },
  blackButton: {
    flex: 1,
    height: 44,
    backgroundColor: '#111827',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  blackButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
});